config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :advertisments do
    resources :comments, :only => [:create, :new, :edit, :update, :destroy]
    member do
      put :change_state
    end
    collection do
      get :cities_for_select
      get :models_for_select
      get :search
      get :autocomplete
    end
  end

  authenticated :user, lambda { |u| u.role == 'admin' } do
    namespace :admin do
      resources :dashboard, only: :index
      resources :users
      resources :types, :countries, :cities, :conditions, :styles, :mileages, :years, :engines, :engine_volumes, :transmissions, 
                :doors, :colors, :makes, :models, :features, except: :show
      resources :advertisments do
        member do
          put :change_state
        end
        collection do
          put :multiple_change_state
          get :moderation
          get :search
        end
      end
    end
  end

  resources :users do
    resources :reviews
    member do
      get :search
    end
  end

  root to: 'advertisments#index'

end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  def index
  end
end

app/views/admin/dashboard/index.html.slim
ul 
  h4 Advertisments panel
  li= link_to 'Advertisments panel', admin_advertisments_path
  li= link_to 'Moderation', moderation_admin_advertisments_path
ul 
  h4 Users panel
  li= link_to 'Show all users', admin_users_path
  li= link_to 'New user', new_admin_user_path
ul 
  h4 Types panel
  li= link_to 'Show all types', admin_types_path
  li= link_to 'New type', new_admin_type_path
ul 
  h4 Makes panel
  li= link_to 'Show all makes', admin_makes_path
  li= link_to 'New make', new_admin_make_path
ul 
  h4 Model panel
  li= link_to 'Show all models', admin_models_path
  li= link_to 'New model', new_admin_model_path
ul 
  h4 Countries panel
  li= link_to 'Show all countries', admin_countries_path
  li= link_to 'New country', new_admin_country_path
ul 
  h4 Cities panel
  li= link_to 'Show all cities', admin_cities_path
  li= link_to 'New city', new_admin_city_path
ul 
  h4 Conditions panel
  li= link_to 'Show all conditions', admin_conditions_path
  li= link_to 'New condition', new_admin_condition_path
ul 
  h4 Styles panel
  li= link_to 'Show all styles', admin_styles_path
  li= link_to 'New style', new_admin_style_path
ul 
  h4 Mileages panel
  li= link_to 'Show all mileages', admin_mileages_path
  li= link_to 'New mileage', new_admin_mileage_path
ul 
  h4 Years panel
  li= link_to 'Show all years', admin_years_path
  li= link_to 'New year', new_admin_year_path
ul 
  h4 Engines panel
  li= link_to 'Show all engines', admin_engines_path
  li= link_to 'New engine', new_admin_engine_path
ul 
  h4 Engine volumes panel
  li= link_to 'Show all volumes', admin_engine_volumes_path
  li= link_to 'New volume', new_admin_engine_volume_path
ul 
  h4 Transmissions panel
  li= link_to 'Show all transmissions', admin_transmissions_path
  li= link_to 'New transmission', new_admin_transmission_path
ul 
  h4 Doors panel
  li= link_to 'Show all doors', admin_doors_path
  li= link_to 'New door', new_admin_door_path
ul 
  h4 Colors panel
  li= link_to 'Show all colors', admin_colors_path
  li= link_to 'New color', new_admin_color_path
ul 
  h4 Features panel
  li= link_to 'Show all features', admin_features_path
  li= link_to 'New feature', new_admin_feature_path