config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :advertisments do
    resources :comments, :only => [:create, :new, :edit, :update, :destroy]
    member do
      put :change_state
    end
    collection do
      get :cities_for_select
      get :models_for_select
      get :search
      get :autocomplete
    end
  end

  authenticated :user, lambda { |u| u.role == 'admin' } do
    namespace :admin do
      resources :dashboard, only: :index
      resources :users
      resources :types, :countries, :cities, :conditions, :styles, :mileages, :years, :engines, :engine_volumes, :transmissions, 
                :doors, :colors, :makes, :models, :features, except: :show
      resources :advertisments do
        member do
          put :change_state
        end
        collection do
          put :multiple_change_state
          get :moderation
          get :search
        end
      end
    end
  end

  resources :users do
    resources :reviews
    member do
      get :search
    end
  end

  root to: 'advertisments#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  extend Enumerize
  has_many :advertisments, dependent: :destroy
  has_many :comments
  has_many :reviews, class_name: "Review", foreign_key: "assignee_id"
  has_many :feedbacks, class_name: "Review", foreign_key: "user_id"
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable

  validates :role, presence: true
  validates :nickname, presence: true, length: { minimum: 3,  maximum: 30 }
  validates :name, presence: true, length: { minimum: 3,  maximum: 30 }
  validates :surname, presence: true, length: { minimum: 3,  maximum: 30 }
  enumerize :role, in: [:user, :admin], default: :user

  def fullname
    name.titleize + ' '+ surname.titleize
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  load_and_authorize_resource

  def index
  end

  def new
  end

  def create
    if @user.save
      flash[:success] = "User #{@user.email} was created!"
      redirect_to @user
    else
      flash[:error] = 'Something wrong'
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "User #{@user.email} was updated!"
      redirect_to @user
    else
      flash[:error] = 'Something wrong'
      render 'edit'
    end
  end

  def delete
  end

  def destroy
    @user.destroy
    flash[:success] = "User #{@user.email} was deleted!"
    redirect_to root_url
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :role, :nickname, :name, :surname)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_resource

  def show
    @advertisments = @user.advertisments
  end

  def search
    @advertisments = Advertisment.where("title ILIKE :title AND state = :state AND user_id = :user_id", title: "%#{params[:search]}%", state: params[:state], user_id: @user.id)
    render :show
  end
end

app/views/users/_search_form.html.slim
= form_tag search_user_path, method: :get do
    .form-group
        = label_tag 'Title'
        .controls
          = text_field_tag :search, params[:search]
    .form-group
      = label_tag 'State'
      .controls
        = select_tag :state, options_for_select(Advertisment.pluck(:state).uniq, params[:search]), include_blank: true
    = submit_tag 'Search', :class => "btn btn-primary"

app/views/users/show.html.slim
- model_class = User
div class="page-header"
p
  strong= model_class.human_attribute_name(:email) + ':'
  br
  = @user.email
p
  strong= model_class.human_attribute_name(:nickname) + ':'
  br
  l= @user.nickname
p
  strong Fullname:
  br
  l= @user.fullname
p
  strong= model_class.human_attribute_name(:role) + ':'
  br
  = @user.role
p
  strong= model_class.human_attribute_name(:created_at) + ':'
  br
  l= @user.created_at
  
div 
  - if @user.reviews.any?
    = link_to "User's reviews", user_reviews_path(@user), class: "btn btn-default"
  - if @user != current_user
    - if can? :create, Review
      = link_to "Create review to this user", new_user_review_path(@user), class: "btn btn-primary"
h4
  br
  = @user.nickname.titleize + ' advertisments'
table#myTable class="table table-striped"
  thead
    tr
      th= model_class.human_attribute_name(:title)
      th= model_class.human_attribute_name(:body)
      th= model_class.human_attribute_name(:type_id)
      th= model_class.human_attribute_name(:state)
      th= model_class.human_attribute_name(:updated_at)
      th=t '.actions', :default => t("helpers.actions")
  tbody
    - @advertisments.each do |advertisment|
      - if can? :read, advertisment
        tr
          td= advertisment.title
          td= advertisment.body
          td= advertisment.type.name
          td= advertisment.state
          td=l advertisment.updated_at
          td
            = link_to t('.show', :default => t("helpers.links.show")), advertisment_path(advertisment), :class => 'btn btn-default btn-xs'
            '
            - if can? :change_state, advertisment
              - if advertisment.state=='sketch'
                = link_to 'Set to moderation', change_state_advertisment_path(advertisment,state_status:'create'), method: :put, :class => 'btn btn-success btn-xs'
              - else
                = link_to 'Recover', change_state_advertisment_path(advertisment,state_status:'recover'), method: :put, :class => 'btn btn-success btn-xs'
            '
            - if can? :edit, advertisment
              = link_to t('.edit', :default => t("helpers.links.edit")), edit_advertisment_path(advertisment), :class => 'btn btn-default btn-xs'
            '
            - if can? :destroy, advertisment
              = link_to t('.destroy', :default => t("helpers.links.destroy")), advertisment_path(advertisment), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'