config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :advertisments do
    resources :comments, :only => [:create, :new, :edit, :update, :destroy]
    member do
      put :change_state
    end
    collection do
      get :cities_for_select
      get :models_for_select
      get :search
      get :autocomplete
    end
  end

  authenticated :user, lambda { |u| u.role == 'admin' } do
    namespace :admin do
      resources :dashboard, only: :index
      resources :users
      resources :types, :countries, :cities, :conditions, :styles, :mileages, :years, :engines, :engine_volumes, :transmissions, 
                :doors, :colors, :makes, :models, :features, except: :show
      resources :advertisments do
        member do
          put :change_state
        end
        collection do
          put :multiple_change_state
          get :moderation
          get :search
        end
      end
    end
  end

  resources :users do
    resources :reviews
    member do
      get :search
    end
  end

  root to: 'advertisments#index'

end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :cars
  has_many :cities
  validates :name, presence: true, length: { maximum: 30 }, uniqueness: true
end

app/controllers/admin/countries_controller.rb
class Admin::CountriesController < ApplicationController
  load_and_authorize_resource

  def index
  end

  def new
  end

  def create
    if @country.save
      flash[:success] = "Country #{@country.name} was created!"
      redirect_to action: 'index'
    else
      flash[:error] = 'Something wrong'
      render 'new'
    end
  end

  def edit
  end

  def update
    if @country.update_attributes(country_params)
      flash[:success] = "Country #{@country.name} was updated!"
      redirect_to action: 'index'
    else
      flash[:error] = 'Something wrong'
      render 'edit'
    end
  end

  def destroy
    @country.destroy
    flash[:success] = 'Country was deleted!'
    redirect_to action: 'index'
  end

  private

  def country_params
    params.require(:country).permit(:name)
  end
end

app/views/admin/countries/_form.html.slim
= form_for [:admin,@country], class: "form form-horizontal country" do |f|
  .form-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'form-control'
    = error_span(@country[:name])
  = f.submit nil, :class => 'btn btn-primary'
  '
  = link_to t('.cancel', :default => t("helpers.links.cancel")), admin_countries_path, :class => 'btn'

app/views/admin/countries/edit.html.slim
- model_class = Country
div class="page-header"
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/admin/countries/index.html.slim
- model_class = Country
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
table#tablecountrys class="table table-striped"
  thead
    tr
      th= model_class.human_attribute_name(:name)
      th=t '.actions', :default => t("helpers.actions")
  tbody
    - @countries.each do |country|
      tr
        td= country.name
        td
          = link_to 'Edit', edit_admin_country_path(country), :class => 'btn btn-default btn-xs'
          '
          - if can? :destroy, country
            = link_to t('.destroy', :default => t("helpers.links.destroy")), admin_country_path(country), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

app/views/admin/countries/new.html.slim
- model_class = Country
div class="page-header"
  h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"