config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :advertisments do
    resources :comments, :only => [:create, :new, :edit, :update, :destroy]
    member do
      put :change_state
    end
    collection do
      get :cities_for_select
      get :models_for_select
      get :search
      get :autocomplete
    end
  end

  authenticated :user, lambda { |u| u.role == 'admin' } do
    namespace :admin do
      resources :dashboard, only: :index
      resources :users
      resources :types, :countries, :cities, :conditions, :styles, :mileages, :years, :engines, :engine_volumes, :transmissions, 
                :doors, :colors, :makes, :models, :features, except: :show
      resources :advertisments do
        member do
          put :change_state
        end
        collection do
          put :multiple_change_state
          get :moderation
          get :search
        end
      end
    end
  end

  resources :users do
    resources :reviews
    member do
      get :search
    end
  end

  root to: 'advertisments#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  extend Enumerize
  has_many :advertisments, dependent: :destroy
  has_many :comments
  has_many :reviews, class_name: "Review", foreign_key: "assignee_id"
  has_many :feedbacks, class_name: "Review", foreign_key: "user_id"
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable

  validates :role, presence: true
  validates :nickname, presence: true, length: { minimum: 3,  maximum: 30 }
  validates :name, presence: true, length: { minimum: 3,  maximum: 30 }
  validates :surname, presence: true, length: { minimum: 3,  maximum: 30 }
  enumerize :role, in: [:user, :admin], default: :user

  def fullname
    name.titleize + ' '+ surname.titleize
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  load_and_authorize_resource

  def index
  end

  def new
  end

  def create
    if @user.save
      flash[:success] = "User #{@user.email} was created!"
      redirect_to @user
    else
      flash[:error] = 'Something wrong'
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "User #{@user.email} was updated!"
      redirect_to @user
    else
      flash[:error] = 'Something wrong'
      render 'edit'
    end
  end

  def delete
  end

  def destroy
    @user.destroy
    flash[:success] = "User #{@user.email} was deleted!"
    redirect_to root_url
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :role, :nickname, :name, :surname)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_resource

  def show
    @advertisments = @user.advertisments
  end

  def search
    @advertisments = Advertisment.where("title ILIKE :title AND state = :state AND user_id = :user_id", title: "%#{params[:search]}%", state: params[:state], user_id: @user.id)
    render :show
  end
end

app/views/admin/users/_form.html.slim
= form_for [:admin,@user], class: "form form-horizontal user" do |f|
  .form-group
    = f.label :email, :class => 'control-label'
    .controls
      = f.text_field :email, autofocus: true, :class => 'form-control'
    = error_span(@user[:email])
  .form-group
    = f.label :password, :class => 'control-label'
    .controls
      = f.text_field :password, :class => 'form-control'
    = error_span(@user[:password])
  .form-group
    = f.label :nickname, :class => 'control-label'
    .controls
      = f.text_field :nickname, autofocus: true, :class => 'form-control'
    = error_span(@user[:nickname])  
  .form-group  
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, autofocus: true, :class => 'form-control'
    = error_span(@user[:name])  
  .form-group  
    = f.label :surname, :class => 'control-label'
    .controls
      = f.text_field :surname, autofocus: true, :class => 'form-control'
    = error_span(@user[:surname])  
  .form-group
    = f.label :role, :class => 'control-label'
    .controls
      = f.select :role, User.role.options, :class => 'form-control'
    = error_span(@user[:role])
  = f.submit nil, :class => 'btn btn-primary'
  '
  = link_to t('.cancel', :default => t("helpers.links.cancel")), admin_users_path, :class => 'btn'

app/views/admin/users/edit.html.slim
- model_class = User
div class="page-header"
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/admin/users/index.html.slim
- model_class = User
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human.pluralize.titleize

table#tableUsers class="table table-striped"
  thead
    tr
      th= model_class.human_attribute_name(:email)
      th= model_class.human_attribute_name(:nickname)
      th= model_class.human_attribute_name(:name)
      th= model_class.human_attribute_name(:surname)
      th= model_class.human_attribute_name(:role)
      th= model_class.human_attribute_name(:sign_in_count)
      th= model_class.human_attribute_name(:created_at)
      th=t '.actions', :default => t("helpers.actions")
  tbody
    - @users.each do |user|
      tr
        td= link_to user.email, admin_user_path(user)
        td= user.nickname
        td= user.name
        td= user.surname
        td= user.role
        td= user.sign_in_count
        td=l user.created_at
        td
          = link_to t('.show', :default => t("helpers.links.show")), admin_user_path(user), :class => 'btn btn-default btn-xs'
          - if can? :edit, user
            = link_to t('.edit', :default => t("helpers.links.edit")), edit_admin_user_path(user), :class => 'btn btn-default btn-xs'
          '
          - if can? :destroy, user
            = link_to t('.destroy', :default => t("helpers.links.destroy")), admin_user_path(user), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

app/views/admin/users/new.html.slim
- model_class = User
div class="page-header"
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/admin/users/show.html.slim
- model_class = User
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human.titleize
p
  strong= model_class.human_attribute_name(:email) + ':'
  br
  = @user.email
p
  strong= model_class.human_attribute_name(:nickname) + ':'
  br
  l= @user.nickname
p
  strong Fullname:
  br
  l= @user.fullname
p
  strong= model_class.human_attribute_name(:role) + ':'
  br
  = @user.role
p
  strong= model_class.human_attribute_name(:created_at) + ':'
  br
  l= @user.created_at
p
  - if @user==current_user
    = link_to t('.edit', :default => t("helpers.links.edit")), edit_user_registration_path, :class => 'btn btn-default'
  - else
    = link_to t('.edit', :default => t("helpers.links.edit")), edit_admin_user_path(@user), :class => 'btn btn-default'
  '
  = link_to t('.destroy', :default => t("helpers.links.destroy")), admin_user_path(@user), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'
p 
  - if @user.role.user?
    = link_to "User's advertisments", user_path(@user), :class => 'btn btn-info'
    